apiVersion: v1
kind: Namespace
metadata:
  name: fos-fe-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fos-fe-namespace
  name: angular-frontend
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular-container
          image: umelon/fos-angular-image
          ports:
            - containerPort: 4200
          command: ["ng", "serve", "--host", "0.0.0.0"]
          volumeMounts:
            - mountPath: /app/dist
              name: angular-storage
      volumes:
        - name: angular-storage
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: fos-fe-namespace
  name: angular-service
spec:
  type: NodePort
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200

